spring.application.name=MusicApp

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.datasource.url=jdbc:postgresql://localhost:5432/MusicApp
spring.datasource.username=postgres
spring.datasource.password=Macieklabuz2002
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=30MB
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
file.upload-dir=D:/mp3
server.tomcat.connection-timeout=60s
server.tomcat.max-connections=200
server.tomcat.max-threads=100
